package my.dolphinapps.greendao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE.
 */
public class Favorite {

    private Long id;
    private String slang;
    private String meaning;

    public Favorite() {
    }

    public Favorite(Long id) {
        this.id = id;
    }

    public Favorite(Long id, String slang, String meaning) {
        this.id = id;
        this.slang = slang;
        this.meaning = meaning;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSlang() {
        return slang;
    }

    public void setSlang(String slang) {
        this.slang = slang;
    }

    public String getMeaning() {
        return meaning;
    }

    public void setMeaning(String meaning) {
        this.meaning = meaning;
    }

}
